# Dependencies
markdown:         kramdown
highlighter:      pygments

# Setup
title:            Joel Niklaus
tagline:          'PHD STUDENT | COMPUTATiONAL LiNGUiSTiCS'
description:      'I am passionate about driving innovation in the field of Artificial Intelligence.'
url:              https://joelniklaus.github.io
baseurl:          /

author:
  name:           'Joel Niklaus'
  url:            https://twitter.com/joelniklaus

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/JoelNiklaus/joelniklaus.github.io


collections:
  pages:
    output: true
    permalink: "/:name"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

gems:
  - jekyll-feed
