# Dependencies
markdown: kramdown
highlighter: pygments

# Setup
title: Joel Niklaus
tagline: 'PhD Student in Natural Language Processing'
description: 'I like applying the latest transformers on multilingual legal documents.'
url: https://joelniklaus.github.io
baseurl: /

author:
  name: 'Joel Niklaus'
  url: https://twitter.com/joelniklaus

# Custom vars
encoding: UTF-8
version: 2.1.0

github-repo: https://github.com/JoelNiklaus/joelniklaus.github.io
github-version: refs/heads/main

collections:
  pages:
    output: true
    permalink: "/:name"
  projects:
    output: true
    permalink: "/project/:slug"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - github-pages
  - jekyll-sitemap

github: [ metadata ]